name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # تعيين مسار Android SDK داخل مساحة العمل
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-8-jdk libffi-dev libssl-dev

      - name: Install Python Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython virtualenv

      - name: Setup Android SDK and Commandline Tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT
          cd $ANDROID_SDK_ROOT
          # تنزيل command line tools من Google
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d cmdline-tools
          # إنشاء مجلد "latest" ونقل المحتويات إلى داخله
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          # قبول رخص Android SDK (إذا حدث خطأ مثل broken pipe لن يتوقف البناء)
          yes | sdkmanager --licenses || true
          sdkmanager "platforms;android-28" "build-tools;28.0.3" "platform-tools"
        shell: bash

      - name: Accept Android Licenses Manually
        run: |
          mkdir -p $ANDROID_SDK_ROOT/licenses
          # هذه القيم هي الأمثلة الشائعة لقبول رخص Android SDK
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license
        shell: bash

      - name: Build APK with Buildozer
        run: |
          buildozer -v android debug
        shell: bash

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyCaptchaApp-APK
          path: bin/*.apk
