name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-8-jdk
          # تثبيت بعض الأدوات اللازمة لبناء التطبيقات
          sudo apt-get install -y libffi-dev libssl-dev

      - name: Install Python Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install buildozer cython virtualenv

      - name: Setup Android SDK and Commandline Tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT
          cd $ANDROID_SDK_ROOT
          # تنزيل command line tools من جوجل (يمكن تعديل الرابط حسب الإصدار)
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d cmdline-tools
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-28" "build-tools;28.0.3" "platform-tools"
        shell: bash

      - name: Build APK with Buildozer
        run: |
          # تأكد من أن ملف buildozer.spec موجود في جذر المشروع
          buildozer -v android debug
        shell: bash

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyCaptchaApp-APK
          path: bin/*.apk
